### ISSUE TITLE
Is there any description about the architect difference between iceoryx and iceoryx2,how iceory2 works without roudi

### ISSUE THREAD

**Issue by sgf201** [eclipse-iceoryx/iceoryx2#226]

**Comment by elfenpiff** [comment]
@sgf201 No, they are not available in the open-source repository. Parts of them will be published to support contributors, but the majority will not.
If you are interested in an iceoryx2 deep dive, please contact info@ekxide.io, and we can set up a meeting.

**Comment by sgf201** [comment]
@elfenpiff 
Thank you for your reply. I am interested in using C++binding or other methods to combine Iceoryx2 with Cyclonedds to create a new version of dds or implement related tasks in RMW for ROS2. I also hope to participate in Iceoryx or Iceoryx2, but I don't know much about Rust.

one question, is it based on a certain language attribute of Rust that Iceoryx2 does not need roudi? Or is it true that refactoring Iceoryx can also achieve none-roudi?

**Comment by elfenpiff** [comment]
@sgf201 

> one question, is it based on a certain language attribute of Rust that Iceoryx2 does not need roudi? Or is it true that refactoring Iceoryx can also achieve none-roudi?

It is also possible to refactor iceoryx so that it does not require a central daemon. But we aimed for iceoryx2 and Rust since we think that this combination has the most promising future.

> I am interested in using C++binding or other methods to combine Iceoryx2 with Cyclonedds to create a new version of dds or implement related tasks in RMW for ROS2.

@elBoberido is currently working on the C and, later, the C++ bindings. They should be available in the next two months. 
When you take a look at our [Roadmap](https://github.com/eclipse-iceoryx/iceoryx2/blob/main/ROADMAP.md) you see that we also plan to have a DDS gateway and a ROS2 RMW binding.

If you are interested, we could cooperate here. As soon as the C API for iceoryx2 stands, we could start with an RMW binding and use the [iceoryx RMW binding](https://github.com/ros2/rmw_iceoryx) as a template. If you like, you could take care of this and would make a lot of iceoryx developers happy :) ...

We try to write then a gateway based on zenoh for network communication. If we are lucky we may have something working at the end of this year.
