### ISSUE TITLE
Reuse existing cargo build with C and C++ bindings

### ISSUE THREAD

**Issue by elBoberido** [eclipse-iceoryx/iceoryx2#559]
## Brief feature description

cmake invokes cargo to build the Rust project instead of using an existing build. This simplifies the life of the developers since they have to invoke only one command but makes life harder for integrators.

Similar to our handling with `iceoryx_hoofs`, a cmake parameter shall be introduced to tell cmake where to look for the Rust artifacts. If they are not found, the cmake shall invoke cargo and build everything from scratch.

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Introduced a new CMake parameter RUST_ARTIFACTS_DIR to specify the location of pre-built Rust artifacts. Modified the build process to use these artifacts if available, otherwise fallback to building from source using cargo.

You can review changes in this commit: https://github.com/wwqwq2313/eclipse-iceoryx-iceoryx2-559/commit/5ab300d461442c6752b23747b73b10e42dad011b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
